In [80]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [54]:
#loading data set
#loading data set
df = pd.read_csv('iris_species.csv')
df.loc[df["Species"]=="Iris-setosa","Species"]=0
df.loc[df["Species"]=="Iris-versicolor","Species"]=1
df.loc[df["Species"]=="Iris-virginica","Species"]=2
X=df.iloc[:,1:5].values
y=df.iloc[:,5].values

print("Shape of X",X.shape)
print("Shape of y",y.shape)
print("Examples of X\n",X[:3])
print("Examples of y\n",y[:3])

Shape of X (150, 4)
Shape of y (150,)
Examples of X
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
Examples of y
 [0 0 0]


In [55]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

# remove categorical_features, it works 100% perfectly
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [69]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print("Shape of X",X_train.shape)
print("Shape of X",y_train.shape)

Shape of X (120, 122)
Shape of X (120,)


In [72]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense


# creating ANN classifier
classifier = Sequential()
# one rule to determine the number of hidden layers
# is to average the number of input and output nodes
classifier.add(Dense(units=6, input_dim=122, kernel_initializer='uniform', activation='relu'))
# Add second hidden layers
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu'))
# output layer
# also replace activation function to sigmoid to have probabilities
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))
# compile the classifier
# adam is a type of SGD
# crossentropy is log loss function, for binary classification, use 'binary_crossentropy' 
# for multiclass classification, use 'categorical_crossentropy'
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [73]:
X_train = np.asarray(X_train).astype(np.float32)
y_train = np.asarray(y_train).astype(np.float32)
X_train
classifier.fit(X_train, y_train, epochs=10, batch_size=10)

Epoch 1/10
12/12 [==============================] - 17s 15ms/step - loss: 0.6917 - accuracy: 0.3215
Epoch 2/10
12/12 [==============================] - 0s 4ms/step - loss: 0.6843 - accuracy: 0.3153
Epoch 3/10
12/12 [==============================] - 0s 2ms/step - loss: 0.6743 - accuracy: 0.2410
Epoch 4/10
12/12 [==============================] - 0s 2ms/step - loss: 0.6642 - accuracy: 0.3174
Epoch 5/10
12/12 [==============================] - 0s 2ms/step - loss: 0.6552 - accuracy: 0.3427
Epoch 6/10
12/12 [==============================] - 0s 3ms/step - loss: 0.6314 - accuracy: 0.3073
Epoch 7/10
12/12 [==============================] - 0s 3ms/step - loss: 0.5945 - accuracy: 0.2963
Epoch 8/10
12/12 [==============================] - 0s 3ms/step - loss: 0.5331 - accuracy: 0.3062
Epoch 9/10
12/12 [==============================] - 0s 3ms/step - loss: 0.4611 - accuracy: 0.2752
Epoch 10/10
12/12 [==============================] - 0s 3ms/step - loss: 0.3674 - accuracy: 0.3045


In [78]:
prediction=classifier.predict(X_test)
length=len(prediction)
y_label=np.argmax(y_test,axis=0)
predict_label=np.argmax(prediction,axis=1)

accuracy=np.sum(y_label==predict_label)/length * 100 
print("Accuracy of the dataset",accuracy )

Accuracy of the dataset 100.0
